TAG: 'Prediction_LC_ODE_Variable'

GPUS: [3]

BATCHSIZE: 1
PRECISION: 16
EPOCHS: 20

N_WORKERS: 8

DATASET:
  VERSION: 'trainval'

TIME_RECEPTIVE_FIELD: 3
N_FUTURE_FRAMES: 4

LIFT:
  # Disable GT depth when no camera is used
  GT_DEPTH: False

GEN:
  # Do not generate per-camera depth for radar/LiDAR-only runs
  GEN_DEPTH: False
  GEN_RANGE: True
  GEN_VOXELS: True

MODEL:
  USE_TRANSFORMER: False
  USE_GRU_ODE: True
  IMPUTE: True
  FUTURE_PRED:
    USE_VARIABLE_ODE_STEP: True
  MODALITY:
    USE_LIDAR: True
    USE_RADAR: False
    # Disable vision module for radar/LiDAR-only testing
    USE_CAMERA: False
  ENCODER:
    NAME: 'efficientnet-b4'
    USE_DEPTH_DISTRIBUTION: True
  LIDAR:
    USE_RANGE: False
    USE_STPN: False
    USE_BESTI: False
  TEMPORAL_MODEL:
    NAME: 'temporal_block'
    INPUT_EGOPOSE: True
  BN_MOMENTUM: 0.05

SEMANTIC_SEG:
  PEDESTRIAN:
    ENABLED: False
  HDMAP:
    ENABLED: False

INSTANCE_FLOW:
  ENABLED: True

PROBABILISTIC:
  ENABLED: True
  METHOD: 'GAUSSIAN'

PLANNING:
  ENABLED: False

FUTURE_DISCOUNT: 0.95

OPTIMIZER:
  LR: 2e-4


PRETRAINED:
   LOAD_WEIGHTS: False
